### PR TITLE
Update OTel to 0.6.0

### PR DESCRIPTION
**Pull request by FrankSpitulski**
This update is based on the branch from https://github.com/lightstep/opentelemetry-exporter-java/pull/55 so it also contains the error tagging.

This updates the opentelemetry version to 0.6.0, renames the packages that have changed, and updates the tests to use the newer SpanData objects since the old ones were removed.

I have tested this locally as well with a springboot web application where it successfully sent the expected spans to my local developer satellite.

### CODE REVIEW

**Comment by FrankSpitulski** [comment]
force push was rebasing on #55

**Comment by malafeev** [comment]
@FrankSpitulski did you test agent (https://github.com/lightstep/opentelemetry-exporter-java/tree/master/auto-exporter) and/or manual configuration?
cc @carlosalberto

**Comment by FrankSpitulski** [comment]
I only tested the agent. I have kind of a weird setup to defer loading config so another set of eyes wouldn't go amiss.

**Comment by FrankSpitulski** [comment]
rebased on #55 again

**Comment by malafeev** [comment]
lgtm, but definitely it needs manual test before releasing.

**Comment by FrankSpitulski** [comment]
rebased on master since #55 was merged

**Comment by FrankSpitulski** [comment]
tested with a [standard springboot app](https://github.com/FrankSpitulski/rest-api-example). okio also needed to be shaded.

**Comment by carlosalberto** [comment]
Why the need to shade okio?

**Comment by FrankSpitulski** [comment]
It was throwing class definition errors on the okhttp builder until I did. Lots of experimentation.

**Review by carlosalberto — APPROVED** [review]

**Review by malafeev — APPROVED** [review]

**Pull request merged**
